cache:
  paths:
    - .terraform
 
stages:
  - deploy

deploy_staging:
  stage: deploy
  tags:
    - terraform
  script:
    - terraform init -backend-config="bucket=${TERRAFORM_S3_BUCKET}"
      -backend-config="region=${TF_VAR_AWS_REGION}" -backend-config="role_arn=arn:aws:iam::${TF_VAR_DEPLOY_INTO_ACCOUNT_ID}:role/S3BackendRole"
      -backend-config="external_id=${TF_VAR_ASSUME_ROLE_EXTERNAL_ID}"
      -backend-config="session_name=TerraformBackend" terraform-configuration
    - terraform apply -auto-approve -input=false terraform-configuration
  environment:
    name: staging
    url: https://staging.example.com
    on_stop: stop_staging
  only:
    variables:
      - $DEPLOY_TO == "staging"

stop_staging:
  stage: deploy
  tags:
    - terraform
  script:
    - terraform destroy -input=false -auto-approve src/main/terraform
  when: manual
  environment:
    name: staging
    action: stop
